[package]
name = "sapling-crypto"
version = "0.4.0"
authors = [
    "Sean Bowe <sean@electriccoin.co>",
    "Jack Grigg <jack@electriccoin.co>",
    "Kris Nuttycombe <kris@electriccoin.co>",
]
edition = "2021"
rust-version = "1.65"
description = "Cryptographic library for Zcash Sapling"
homepage = "https://github.com/zcash/sapling-crypto"
repository = "https://github.com/zcash/sapling-crypto"
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
features = ["test-dependencies"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
ff = "0.13"
group = { version = "0.13", features = ["wnaf-memuse"] }

bls12_381 = "0.8"
jubjub = "0.10"
redjubjub = "0.7"
zcash_spec = "0.1"

# Boilerplate
getset = "0.1"

# Circuits
bellman = { version = "0.14", default-features = false, features = ["groth16"] }

# CSPRNG
rand = "0.8"
rand_core = "0.6"

# Digests
blake2b_simd = "1"
blake2s_simd = "1"

# Documentation
document-features = "0.2"

# Encodings
byteorder = "1"
hex = "0.4"

# Logging and metrics
memuse = "0.2.1"
tracing = "0.1"

# Note Commitment Trees
bitvec = "1"
incrementalmerkletree = { version = "0.7", features = ["legacy-api"] }

# Note encryption
zcash_note_encryption = { version = "0.4", features = ["pre-zip-212"] }

# Secret management
subtle = "2.2.3"

# Static constants
lazy_static = "1"

# Test dependencies
proptest = { version = "1", optional = true }

# ZIP 32
aes = "0.8"
fpe = "0.6"
zip32 = "0.1"

[dev-dependencies]
chacha20poly1305 = "0.10"
criterion = "0.4"
incrementalmerkletree = { version = "0.7", features = ["legacy-api", "test-dependencies"] }
proptest = "1"
rand_xorshift = "0.3"

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.11", features = ["criterion", "flamegraph"] } # MSRV 1.56

[features]
default = ["multicore"]

## Enables multithreading support for creating proofs.
multicore = ["bellman/multicore"]

### A temporary feature flag that exposes granular APIs needed by `zcashd`. These APIs
### should not be relied upon and will be removed in a future release.
temporary-zcashd = []

## Exposes APIs that are useful for testing, such as `proptest` strategies.
test-dependencies = [
    "incrementalmerkletree/test-dependencies",
    "dep:proptest",
]

[[bench]]
name = "circuit"
harness = false

[[bench]]
name = "pedersen_hash"
harness = false
